/// [Countries] has a static method [countryList] that returns list of Map for most country around the world.
class Countries {
  /// returns `List<Map<String, dynamic>` of countries which contains
  ///  *  num_code
  ///  *  alpha_2_code
  ///  *  alpha_3_code
  ///  *  en_short_name
  ///  *  nationality
  ///  *  dial_code
  ///  *  nameTranslations
  ///
  ///   ```dart
  ///     {
  ///    "num_code": "566",
  ///    "alpha_2_code": "NG",
  ///    "alpha_3_code": "NGA",
  ///    "en_short_name": "Nigeria",
  ///    "nationality": "Nigerian",
  ///    "dial_code": "+234",
  ///    "nameTranslations": {
  ///      "sk": "Nigéria",
  ///      "se": "Nigeria",
  ///      "pl": "Nigeria",
  ///      "no": "Nigeria",
  ///      "ja": "ナイジェリア",
  ///      "it": "Nigeria",
  ///      "zh": "尼日利亚",
  ///      "nl": "Nigeria",
  ///      "de": "Nigeria",
  ///      "fr": "Nigéria",
  ///      "es": "Nigeria",
  ///      "en": "Nigeria",
  ///      "pt_BR": "Nigéria",
  ///      "sr-Cyrl": "Нигерија",
  ///      "sr-Latn": "Nigerija",
  ///      "zh_TW": "奈及利亞",
  ///      "ar": "نيجيريا",
  ///      "fa": "نیجریه"
  ///        }
  ///     }
  ///   ```
  ///
  static List<Map<String, dynamic>> get countryList => _countryList;

  static List<Map<String, dynamic>> _countryList = [
    {
      "num_code": "203",
      "alpha_2_code": "CZ",
      "alpha_3_code": "CZE",
      "en_short_name": "Czech Republic",
      "nationality": "Czech",
      "dial_code": "+420",
      "nameTranslations": {
        "sk": "Česko",
        "cs": "Česko",
        "se": "Čeahkka",
        "pl": "Czechy",
        "no": "Tsjekkia",
        "ja": "チェコ",
        "it": "Cechia",
        "zh": "捷克",
        "nl": "Tsjechië",
        "de": "Tschechien",
        "fr": "Tchéquie",
        "es": "Chequia",
        "en": "Czechia",
        "pt_BR": "Czechia",
        "sr-Cyrl": "Чешка",
        "sr-Latn": "Češka",
        "zh_TW": "捷克",
        "tr": "Çek Cumhuriyeti",
        "ro": "Cehia",
        "ar": "جمهورية التشيك",
        "fa": "جمهوری چک",
        "yue": "捷克共和國"
      }
    },
    {
      "num_code": "703",
      "alpha_2_code": "SK",
      "alpha_3_code": "SVK",
      "en_short_name": "Slovakia",
      "nationality": "Slovak",
      "dial_code": "+421",
      "nameTranslations": {
        "sk": "Slovensko",
        "cs": "Slovensko",
        "se": "Slovákia",
        "pl": "Słowacja",
        "no": "Slovakia",
        "ja": "スロバキア",
        "it": "Slovacchia",
        "zh": "斯洛伐克",
        "nl": "Slowakije",
        "de": "Slowakei",
        "fr": "Slovaquie",
        "es": "Eslovaquia",
        "en": "Slovakia",
        "pt_BR": "Eslováquia",
        "sr-Cyrl": "Словачка",
        "sr-Latn": "Slovačka",
        "zh_TW": "斯洛伐克",
        "tr": "Slovakya",
        "ro": "Slovacia",
        "ar": "سلوفاكيا",
        "fa": "اسلواکی",
        "yue": "斯洛伐克"
      }
    },
    {
      "num_code": "276",
      "alpha_2_code": "DE",
      "alpha_3_code": "DEU",
      "en_short_name": "Germany",
      "nationality": "German",
      "dial_code": "+49",
      "nameTranslations": {
        "sk": "Nemecko",
        "cs": "Německo",
        "se": "Duiska",
        "pl": "Niemcy",
        "no": "Tyskland",
        "ja": "ドイツ",
        "it": "Germania",
        "zh": "德国",
        "nl": "Duitsland",
        "de": "Deutschland",
        "fr": "Allemagne",
        "es": "Alemania",
        "en": "Germany",
        "pt_BR": "Alemanha",
        "sr-Cyrl": "Немачка",
        "sr-Latn": "Nemačka",
        "zh_TW": "德國",
        "tr": "Almanya",
        "ro": "Germania",
        "ar": "ألمانيا",
        "fa": "آلمان",
        "yue": "德國"
      }
    },
    {
      "num_code": "40",
      "alpha_2_code": "AT",
      "alpha_3_code": "AUT",
      "en_short_name": "Austria",
      "nationality": "Austrian",
      "dial_code": "+43",
      "nameTranslations": {
        "sk": "Rakúsko",
        "cs": "Rakousko",
        "se": "Nuortariika",
        "pl": "Austria",
        "no": "Østerrike",
        "ja": "オーストリア",
        "it": "Austria",
        "zh": "奥地利",
        "nl": "Oostenrijk",
        "de": "Österreich",
        "fr": "Autriche",
        "es": "Austria",
        "en": "Austria",
        "pt_BR": "Áustria",
        "sr-Cyrl": "Аустрија",
        "sr-Latn": "Austrija",
        "zh_TW": "奥地利",
        "tr": "Avusturya",
        "ro": "Austria",
        "ar": "النمسا",
        "fa": "اتریش",
        "yue": "奧地利"
      }
    },
    {
      "num_code": "616",
      "alpha_2_code": "PL",
      "alpha_3_code": "POL",
      "en_short_name": "Poland",
      "nationality": "Polish",
      "dial_code": "+48",
      "nameTranslations": {
        "sk": "Poľsko",
        "cs": "Polsko",
        "se": "Polen",
        "pl": "Polska",
        "no": "Polen",
        "ja": "ポーランド",
        "it": "Polonia",
        "zh": "波兰",
        "nl": "Polen",
        "de": "Polen",
        "fr": "Pologne",
        "es": "Polonia",
        "en": "Poland",
        "pt_BR": "Polônia",
        "sr-Cyrl": "Пољска",
        "sr-Latn": "Poljska",
        "zh_TW": "波蘭",
        "tr": "Polonya",
        "ro": "Polonia",
        "ar": "بولندا",
        "fa": "لهستان",
        "yue": "波蘭"
      }
    },
    {
      "num_code": "348",
      "alpha_2_code": "HU",
      "alpha_3_code": "HUN",
      "en_short_name": "Hungary",
      "nationality": "Hungarian, Magyar",
      "dial_code": "+36",
      "nameTranslations": {
        "sk": "Maďarsko",
        "se": "Ungár",
        "pl": "Węgry",
        "no": "Ungarn",
        "ja": "ハンガリー",
        "it": "Ungheria",
        "zh": "匈牙利",
        "nl": "Hongarije",
        "de": "Ungarn",
        "fr": "Hongrie",
        "es": "Hungría",
        "en": "Hungary",
        "pt_BR": "Hungria",
        "sr-Cyrl": "Мађарска",
        "sr-Latn": "Mađarska",
        "zh_TW": "匈牙利",
        "tr": "Macaristan",
        "ro": "Ungaria",
        "ar": "المجر",
        "fa": "مجارستان",
        "yue": "匈牙利"
      }
    },
    {
      "num_code": "380",
      "alpha_2_code": "IT",
      "alpha_3_code": "ITA",
      "en_short_name": "Italy",
      "nationality": "Italian",
      "dial_code": "+39",
      "nameTranslations": {
        "sk": "Taliansko",
        "se": "Itália",
        "pl": "Włochy",
        "no": "Italia",
        "ja": "イタリア",
        "it": "Italia",
        "zh": "意大利",
        "nl": "Italië",
        "de": "Italien",
        "fr": "Italie",
        "es": "Italia",
        "en": "Italy",
        "pt_BR": "Itália",
        "sr-Cyrl": "Италија",
        "sr-Latn": "Italija",
        "zh_TW": "義大利",
        "tr": "İtalya",
        "ro": "Italia",
        "ar": "إيطاليا",
        "fa": "ایتالیا",
        "yue": "意大利"
      }
    },
    {
      "num_code": "8",
      "alpha_2_code": "AL",
      "alpha_3_code": "ALB",
      "en_short_name": "Albania",
      "nationality": "Albanian",
      "dial_code": "+355",
      "nameTranslations": {
        "sk": "Albánsko",
        "se": "Albánia",
        "pl": "Albania",
        "no": "Albania",
        "ja": "アルバニア",
        "it": "Albania",
        "zh": "阿尔巴尼亚",
        "nl": "Albanië",
        "de": "Albanien",
        "fr": "Albanie",
        "es": "Albania",
        "en": "Albania",
        "pt_BR": "Albânia",
        "sr-Cyrl": "Албанија",
        "sr-Latn": "Albanija",
        "zh_TW": "阿爾巴尼亞",
        "tr": "Arnavutluk",
        "ro": "Albania",
        "ar": "ألبانيا",
        "fa": "آلبانی",
        "yue": "阿爾巴尼亞"
      }
    },
    {
      "num_code": "51",
      "alpha_2_code": "AM",
      "alpha_3_code": "ARM",
      "en_short_name": "Armenia",
      "nationality": "Armenian",
      "dial_code": "+374",
      "nameTranslations": {
        "sk": "Arménsko",
        "se": "Armenia",
        "pl": "Armenia",
        "no": "Armenia",
        "ja": "アルメニア",
        "it": "Armenia",
        "zh": "亚美尼亚",
        "nl": "Armenië",
        "de": "Armenien",
        "fr": "Arménie",
        "es": "Armenia",
        "en": "Armenia",
        "pt_BR": "Armênia",
        "sr-Cyrl": "Јерменија",
        "sr-Latn": "Jermenija",
        "zh_TW": "亞美尼亞",
        "tr": "Ermenistan",
        "ro": "Armenia",
        "ar": "أرمينيا",
        "fa": "ارمنستان",
        "yue": "亞美尼亞"
      }
    },
    {
      "num_code": "36",
      "alpha_2_code": "AU",
      "alpha_3_code": "AUS",
      "en_short_name": "Australia",
      "nationality": "Australian",
      "dial_code": "+61",
      "nameTranslations": {
        "sk": "Austrália",
        "se": "Austrália",
        "pl": "Australia",
        "no": "Australia",
        "ja": "オーストラリア",
        "it": "Australia",
        "zh": "澳大利亚",
        "nl": "Australië",
        "de": "Australien",
        "fr": "Australie",
        "es": "Australia",
        "en": "Australia",
        "pt_BR": "Austrália",
        "sr-Cyrl": "Аустралија",
        "sr-Latn": "Australija",
        "zh_TW": "澳州",
        "tr": "Avustralya",
        "ro": "Australia",
        "ar": "أستراليا",
        "fa": "استرالیا",
        "yue": "澳洲"
      }
    },
    {
      "num_code": "112",
      "alpha_2_code": "BY",
      "alpha_3_code": "BLR",
      "en_short_name": "Belarus",
      "nationality": "Belarusian",
      "dial_code": "+375",
      "nameTranslations": {
        "sk": "Bielorusko",
        "se": "Vilges-Ruošša",
        "pl": "Białoruś",
        "no": "Hviterussland",
        "ja": "ベラルーシ",
        "it": "Bielorussia",
        "zh": "白俄罗斯",
        "nl": "Belarus",
        "de": "Belarus",
        "fr": "Biélorussie",
        "es": "Bielorrusia",
        "en": "Belarus",
        "pt_BR": "Bielo-Rússia",
        "sr-Cyrl": "Белорусија",
        "sr-Latn": "Belorusija",
        "zh_TW": "白俄羅斯",
        "tr": "Belarus",
        "ro": "Belarus",
        "ar": "بيلاروس",
        "fa": "بلاروس",
        "yue": "白俄羅斯"
      }
    },
    {
      "num_code": "56",
      "alpha_2_code": "BE",
      "alpha_3_code": "BEL",
      "en_short_name": "Belgium",
      "nationality": "Belgian",
      "dial_code": "+32",
      "nameTranslations": {
        "sk": "Belgicko",
        "se": "Belgia",
        "pl": "Belgia",
        "no": "Belgia",
        "ja": "ベルギー",
        "it": "Belgio",
        "zh": "比利时",
        "nl": "België",
        "de": "Belgien",
        "fr": "Belgique",
        "es": "Bélgica",
        "en": "Belgium",
        "pt_BR": "Bélgica",
        "sr-Cyrl": "Белгија",
        "sr-Latn": "Belgija",
        "zh_TW": "比利時",
        "tr": "Belçika",
        "ro": "Belgia",
        "ar": "بلجيكا",
        "fa": "بلژیک",
        "yue": "比利時"
      }
    },
    {
      "num_code": "70",
      "alpha_2_code": "BA",
      "alpha_3_code": "BIH",
      "en_short_name": "Bosnia and Herzegovina",
      "nationality": "Bosnian or Herzegovinian",
      "dial_code": "+387",
      "nameTranslations": {
        "sk": "Bosna a Hercegovina",
        "se": "Bosnia-Hercegovina",
        "pl": "Bośnia i Hercegowina",
        "no": "Bosnia-Hercegovina",
        "ja": "ボスニア・ヘルツェゴビナ",
        "it": "Bosnia ed Erzegovina",
        "zh": "波斯尼亚和黑塞哥维那",
        "nl": "Bosnië en Herzegovina",
        "de": "Bosnien und Herzegowina",
        "fr": "Bosnie-Herzégovine",
        "es": "Bosnia y Herzegovina",
        "en": "Bosnia & Herzegovina",
        "pt_BR": "Bósnia e Herzegovina",
        "sr-Cyrl": "Босна и Херцеговина",
        "sr-Latn": "Bosna i Hercegovina",
        "zh_TW": "波士尼亞和黑塞哥維那",
        "tr": "Bosna Hersek",
        "ro": "Bosnia și Herțegovina",
        "ar": "البوسنة والهرسك",
        "fa": "بوسنی و هرزگوین",
        "yue": "波斯尼亞黑塞哥維那"
      }
    },
    {
      "num_code": "124",
      "alpha_2_code": "CA",
      "alpha_3_code": "CAN",
      "en_short_name": "Canada",
      "nationality": "Canadian",
      "dial_code": "+1",
      "nameTranslations": {
        "sk": "Kanada",
        "se": "Kanáda",
        "pl": "Kanada",
        "no": "Canada",
        "ja": "カナダ",
        "it": "Canada",
        "zh": "加拿大",
        "nl": "Canada",
        "de": "Kanada",
        "fr": "Canada",
        "es": "Canadá",
        "en": "Canada",
        "pt_BR": "Canadá",
        "sr-Cyrl": "Канада",
        "sr-Latn": "Kanada",
        "zh_TW": "加拿大",
        "tr": "Kanada",
        "ro": "Canada",
        "ar": "كندا",
        "fa": "کانادا",
        "yue": "加拿大"
      }
    },
    {
      "num_code": "191",
      "alpha_2_code": "HR",
      "alpha_3_code": "HRV",
      "en_short_name": "Croatia",
      "nationality": "Croatian",
      "dial_code": "+385",
      "nameTranslations": {
        "sk": "Chorvátsko",
        "se": "Kroátia",
        "pl": "Chorwacja",
        "no": "Kroatia",
        "ja": "クロアチア",
        "it": "Croazia",
        "zh": "克罗地亚",
        "nl": "Kroatië",
        "de": "Kroatien",
        "fr": "Croatie",
        "es": "Croacia",
        "en": "Croatia",
        "pt_BR": "Croácia",
        "sr-Cyrl": "Хрватска",
        "sr-Latn": "Hrvatska",
        "zh_TW": "克羅埃西亞",
        "tr": "Hırvatistan",
        "ro": "Croația",
        "ar": "كرواتيا",
        "fa": "کرواسی",
        "yue": "克羅地亞"
      }
    },
    {
      "num_code": "196",
      "alpha_2_code": "CY",
      "alpha_3_code": "CYP",
      "en_short_name": "Cyprus",
      "nationality": "Cypriot",
      "dial_code": "+357",
      "nameTranslations": {
        "sk": "Cyprus",
        "se": "Kypros",
        "pl": "Cypr",
        "no": "Kypros",
        "ja": "キプロス",
        "it": "Cipro",
        "zh": "塞浦路斯",
        "nl": "Cyprus",
        "de": "Zypern",
        "fr": "Chypre",
        "es": "Chipre",
        "en": "Cyprus",
        "pt_BR": "Chipre",
        "sr-Cyrl": "Кипар",
        "sr-Latn": "Kipar",
        "zh_TW": "塞普勒斯",
        "tr": "Kıbrıs",
        "ro": "Cipru",
        "ar": "قبرص",
        "fa": "قبرس",
        "yue": "塞浦路斯"
      }
    },
    {
      "num_code": "208",
      "alpha_2_code": "DK",
      "alpha_3_code": "DNK",
      "en_short_name": "Denmark",
      "nationality": "Danish",
      "dial_code": "+45",
      "nameTranslations": {
        "sk": "Dánsko",
        "se": "Dánmárku",
        "pl": "Dania",
        "no": "Danmark",
        "ja": "デンマーク",
        "it": "Danimarca",
        "zh": "丹麦",
        "nl": "Denemarken",
        "de": "Dänemark",
        "fr": "Danemark",
        "es": "Dinamarca",
        "en": "Denmark",
        "pt_BR": "Dinamarca",
        "sr-Cyrl": "Данска",
        "sr-Latn": "Danska",
        "zh_TW": "丹麥",
        "tr": "Danimarka",
        "ro": "Danemarca",
        "ar": "الدنمارك",
        "fa": "دانمارک",
        "yue": "丹麥"
      }
    },
    {
      "num_code": "233",
      "alpha_2_code": "EE",
      "alpha_3_code": "EST",
      "en_short_name": "Estonia",
      "nationality": "Estonian",
      "dial_code": "+372",
      "nameTranslations": {
        "sk": "Estónsko",
        "se": "Estlánda",
        "pl": "Estonia",
        "no": "Estland",
        "ja": "エストニア",
        "it": "Estonia",
        "zh": "爱沙尼亚",
        "nl": "Estland",
        "de": "Estland",
        "fr": "Estonie",
        "es": "Estonia",
        "en": "Estonia",
        "pt_BR": "Estônia",
        "sr-Cyrl": "Естонија",
        "sr-Latn": "Estonija",
        "zh_TW": "愛沙尼亞",
        "tr": "Estonya",
        "ro": "Estonia",
        "ar": "إستونيا",
        "fa": "استونی",
        "yue": "愛沙尼亞"
      }
    },
    {
      "num_code": "246",
      "alpha_2_code": "FI",
      "alpha_3_code": "FIN",
      "en_short_name": "Finland",
      "nationality": "Finnish",
      "dial_code": "+358",
      "nameTranslations": {
        "sk": "Fínsko",
        "se": "Suopma",
        "pl": "Finlandia",
        "no": "Finland",
        "ja": "フィンランド",
        "it": "Finlandia",
        "zh": "芬兰",
        "nl": "Finland",
        "de": "Finnland",
        "fr": "Finlande",
        "es": "Finlandia",
        "en": "Finland",
        "pt_BR": "Finlândia",
        "sr-Cyrl": "Финска",
        "sr-Latn": "Finska",
        "zh_TW": "芬蘭",
        "tr": "Finlandiya",
        "ro": "Finlanda",
        "ar": "فنلندا",
        "fa": "فنلاند",
        "yue": "芬蘭"
      }
    },
    {
      "num_code": "250",
      "alpha_2_code": "FR",
      "alpha_3_code": "FRA",
      "en_short_name": "France",
      "nationality": "French",
      "dial_code": "+33",
      "nameTranslations": {
        "sk": "Francúzsko",
        "se": "Frankriika",
        "pl": "Francja",
        "no": "Frankrike",
        "ja": "フランス",
        "it": "Francia",
        "zh": "法国",
        "nl": "Frankrijk",
        "de": "Frankreich",
        "fr": "France",
        "es": "Francia",
        "en": "France",
        "pt_BR": "França",
        "sr-Cyrl": "Француска",
        "sr-Latn": "Francuska",
        "zh_TW": "法國",
        "tr": "Fransa",
        "ro": "Franța",
        "ar": "فرنسا",
        "fa": "فرانسه",
        "yue": "法國"
      }
    },
    {
      "num_code": "292",
      "alpha_2_code": "GI",
      "alpha_3_code": "GIB",
      "en_short_name": "Gibraltar",
      "nationality": "Gibraltar",
      "dial_code": "+350",
      "nameTranslations": {
        "sk": "Gibraltár",
        "se": "Gibraltar",
        "pl": "Gibraltar",
        "no": "Gibraltar",
        "ja": "ジブラルタル",
        "it": "Gibilterra",
        "zh": "直布罗陀",
        "nl": "Gibraltar",
        "de": "Gibraltar",
        "fr": "Gibraltar",
        "es": "Gibraltar",
        "en": "Gibraltar",
        "pt_BR": "Gibraltar",
        "sr-Cyrl": "Гибралтар",
        "sr-Latn": "Gibraltar",
        "zh_TW": "直布羅陀",
        "tr": "Cebelitarık",
        "ro": "Gibraltar",
        "ar": "جبل طارق",
        "fa": "جبل الطارق",
        "yue": "直布羅陀"
      }
    },
    {
      "num_code": "300",
      "alpha_2_code": "GR",
      "alpha_3_code": "GRC",
      "en_short_name": "Greece",
      "nationality": "Greek, Hellenic",
      "dial_code": "+30",
      "nameTranslations": {
        "sk": "Grécko",
        "se": "Greika",
        "pl": "Grecja",
        "no": "Hellas",
        "ja": "ギリシャ",
        "it": "Grecia",
        "zh": "希腊",
        "nl": "Griekenland",
        "de": "Griechenland",
        "fr": "Grèce",
        "es": "Grecia",
        "en": "Greece",
        "pt_BR": "Grécia",
        "sr-Cyrl": "Грчка",
        "sr-Latn": "Grčka",
        "zh_TW": "希臘",
        "tr": "Yunanistan",
        "ro": "Grecia",
        "ar": "اليونان",
        "fa": "یونان",
        "yue": "希臘"
      }
    },
    {
      "num_code": "304",
      "alpha_2_code": "GL",
      "alpha_3_code": "GRL",
      "en_short_name": "Greenland",
      "nationality": "Greenlandic",
      "dial_code": "+299",
      "nameTranslations": {
        "sk": "Grónsko",
        "se": "Kalaallit Nunaat",
        "pl": "Grenlandia",
        "no": "Grønland",
        "ja": "グリーンランド",
        "it": "Groenlandia",
        "zh": "格陵兰",
        "nl": "Groenland",
        "de": "Grönland",
        "fr": "Groenland",
        "es": "Groenlandia",
        "en": "Greenland",
        "pt_BR": "Groenlândia",
        "sr-Cyrl": "Гренланд",
        "sr-Latn": "Grenland",
        "zh_TW": "格陵蘭",
        "tr": "Grönland",
        "ro": "Groenlanda",
        "ar": "جرينلاند",
        "fa": "گرینلند",
        "yue": "格陵蘭"
      }
    },
    {
      "num_code": "336",
      "alpha_2_code": "VA",
      "alpha_3_code": "VAT",
      "en_short_name": "Vatican City State",
      "nationality": "Vatican",
      "dial_code": "+379",
      "nameTranslations": {
        "sk": "Vatikán",
        "se": "Vatikána",
        "pl": "Watykan",
        "no": "Vatikanstaten",
        "ja": "バチカン市国",
        "it": "Città del Vaticano",
        "zh": "梵蒂冈",
        "nl": "Vaticaanstad",
        "de": "Vatikanstadt",
        "fr": "État de la Cité du Vatican",
        "es": "Ciudad del Vaticano",
        "en": "Vatican City",
        "pt_BR": "Cidade do Vaticano",
        "sr-Cyrl": "Ватикан",
        "sr-Latn": "Vatikan",
        "zh_TW": "梵蒂岡",
        "tr": "Vatikan",
        "ro": "Vatican",
        "ar": "الفاتيكان",
        "fa": "واتیکان",
        "yue": "梵蒂岡城國"
      }
    },
    {
      "num_code": "352",
      "alpha_2_code": "IS",
      "alpha_3_code": "ISL",
      "en_short_name": "Iceland",
      "nationality": "Icelandic",
      "dial_code": "+354",
      "nameTranslations": {
        "sk": "Island",
        "se": "Islánda",
        "pl": "Islandia",
        "no": "Island",
        "ja": "アイスランド",
        "it": "Islanda",
        "zh": "冰岛",
        "nl": "IJsland",
        "de": "Island",
        "fr": "Islande",
        "es": "Islandia",
        "en": "Iceland",
        "pt_BR": "Islândia",
        "sr-Cyrl": "Исланд",
        "sr-Latn": "Island",
        "zh_TW": "冰島",
        "tr": "İzlanda",
        "ro": "Islanda",
        "ar": "آيسلندا",
        "fa": "ایسلند",
        "yue": "冰島"
      }
    },
    {
      "num_code": "372",
      "alpha_2_code": "IE",
      "alpha_3_code": "IRL",
      "en_short_name": "Ireland",
      "nationality": "Irish",
      "dial_code": "+353",
      "nameTranslations": {
        "sk": "Írsko",
        "se": "Irlánda",
        "pl": "Irlandia",
        "no": "Irland",
        "ja": "アイルランド",
        "it": "Irlanda",
        "zh": "爱尔兰",
        "nl": "Ierland",
        "de": "Irland",
        "fr": "Irlande",
        "es": "Irlanda",
        "en": "Ireland",
        "pt_BR": "Irlanda",
        "sr-Cyrl": "Ирска",
        "sr-Latn": "Irska",
        "zh_TW": "愛爾蘭",
        "tr": "İrlanda",
        "ro": "Irlanda",
        "ar": "أيرلندا",
        "fa": "ایرلند",
        "yue": "愛爾蘭"
      }
    },
    {
      "num_code": "833",
      "alpha_2_code": "IM",
      "alpha_3_code": "IMN",
      "en_short_name": "Isle of Man",
      "nationality": "Manx",
      "dial_code": "+44",
      "nameTranslations": {
        "sk": "Ostrov Man",
        "se": "Mann-sullot",
        "pl": "Wyspa Man",
        "no": "Man",
        "ja": "マン島",
        "it": "Isola di Man",
        "zh": "马恩岛",
        "nl": "Isle of Man",
        "de": "Isle of Man",
        "fr": "Île de Man",
        "es": "Isla de Man",
        "en": "Isle of Man",
        "pt_BR": "Ilha de Man",
        "sr-Cyrl": "Острво Мен",
        "sr-Latn": "Ostrvo Men",
        "zh_TW": "曼島",
        "tr": "Man Adası",
        "ro": "Insula Man",
        "ar": "جزيرة مان",
        "fa": "جزیره مان",
        "yue": "马伊岛"
      }
    },
    {
      "num_code": "392",
      "alpha_2_code": "JP",
      "alpha_3_code": "JPN",
      "en_short_name": "Japan",
      "nationality": "Japanese",
      "dial_code": "+81",
      "nameTranslations": {
        "sk": "Japonsko",
        "se": "Japána",
        "pl": "Japonia",
        "no": "Japan",
        "ja": "日本",
        "it": "Giappone",
        "zh": "日本",
        "nl": "Japan",
        "de": "Japan",
        "fr": "Japon",
        "es": "Japón",
        "en": "Japan",
        "pt_BR": "Japão",
        "sr-Cyrl": "Јапан",
        "sr-Latn": "Japan",
        "zh_TW": "日本",
        "tr": "Japonya",
        "ro": "Japonia",
        "ar": "اليابان",
        "fa": "ژاپن",
        "yue": "日本"
      }
    },
    {
      "num_code": "398",
      "alpha_2_code": "KZ",
      "alpha_3_code": "KAZ",
      "en_short_name": "Kazakhstan",
      "nationality": "Kazakhstani, Kazakh",
      "dial_code": "+7",
      "nameTranslations": {
        "sk": "Kazachstan",
        "se": "Kasakstan",
        "pl": "Kazachstan",
        "no": "Kasakhstan",
        "ja": "カザフスタン",
        "it": "Kazakistan",
        "zh": "哈萨克斯坦",
        "nl": "Kazachstan",
        "de": "Kasachstan",
        "fr": "Kazakhstan",
        "es": "Kazajistán",
        "en": "Kazakhstan",
        "pt_BR": "Cazaquistão",
        "sr-Cyrl": "Казахстан",
        "sr-Latn": "Kazahstan",
        "zh_TW": "哈薩克",
        "tr": "Kazakistan",
        "ro": "Kazahstan",
        "ar": "كازاخستان",
        "fa": "قزاقستان",
        "yue": "哈薩克斯坦"
      }
    },
    {
      "num_code": "410",
      "alpha_2_code": "KR",
      "alpha_3_code": "KOR",
      "en_short_name": "Korea (Republic of)",
      "nationality": "South Korean",
      "dial_code": "+82",
      "nameTranslations": {
        "sk": "Južná Kórea",
        "se": "Mátta-Korea",
        "pl": "Korea Południowa",
        "no": "Sør-Korea",
        "ja": "韓国",
        "it": "Corea del Sud",
        "zh": "韩国",
        "nl": "Zuid-Korea",
        "de": "Südkorea",
        "fr": "Corée du Sud",
        "es": "Corea del Sur",
        "en": "South Korea",
        "pt_BR": "Coreia do Sul",
        "sr-Cyrl": "Јужна Кореја",
        "sr-Latn": "Južna Koreja",
        "zh_TW": "南韓",
        "tr": "Güney Kore",
        "ro": "Coreea de Sud",
        "ar": "كوريا الجنوبية",
        "fa": "کره جنوبی",
        "yue": "韓國（大韓民國）"
      }
    },
    {
      "num_code": "417",
      "alpha_2_code": "KG",
      "alpha_3_code": "KGZ",
      "en_short_name": "Kyrgyzstan",
      "nationality": "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz",
      "dial_code": "+996",
      "nameTranslations": {
        "sk": "Kirgizsko",
        "se": "Kirgisistan",
        "pl": "Kirgistan",
        "no": "Kirgisistan",
        "ja": "キルギス",
        "it": "Kirghizistan",
        "zh": "吉尔吉斯斯坦",
        "nl": "Kirgizië",
        "de": "Kirgisistan",
        "fr": "Kirghizistan",
        "es": "Kirguistán",
        "en": "Kyrgyzstan",
        "pt_BR": "Quirguistão",
        "sr-Cyrl": "Киргистан",
        "sr-Latn": "Kirgistan",
        "zh_TW": "吉爾吉斯",
        "tr": "Kırgızistan",
        "ro": "Kîrgîzstan",
        "ar": "قيرغيزستان",
        "fa": "قرقیزستان",
        "yue": "吉爾吉斯斯坦"
      }
    },
    {
      "num_code": "428",
      "alpha_2_code": "LV",
      "alpha_3_code": "LVA",
      "en_short_name": "Latvia",
      "nationality": "Latvian",
      "dial_code": "+371",
      "nameTranslations": {
        "sk": "Lotyšsko",
        "se": "Látvia",
        "pl": "Łotwa",
        "no": "Latvia",
        "ja": "ラトビア",
        "it": "Lettonia",
        "zh": "拉脱维亚",
        "nl": "Letland",
        "de": "Lettland",
        "fr": "Lettonie",
        "es": "Letonia",
        "en": "Latvia",
        "pt_BR": "Letônia",
        "sr-Cyrl": "Летонија",
        "sr-Latn": "Letonija",
        "zh_TW": "拉托維亞",
        "tr": "Letonya",
        "ro": "Letonia",
        "ar": "لاتفيا",
        "fa": "لتونی",
        "yue": "拉脫維亞"
      }
    },
    {
      "num_code": "422",
      "alpha_2_code": "LB",
      "alpha_3_code": "LBN",
      "en_short_name": "Lebanon",
      "nationality": "Lebanese",
      "dial_code": "+961",
      "nameTranslations": {
        "sk": "Libanon",
        "se": "Libanon",
        "pl": "Liban",
        "no": "Libanon",
        "ja": "レバノン",
        "it": "Libano",
        "zh": "黎巴嫩",
        "nl": "Libanon",
        "de": "Libanon",
        "fr": "Liban",
        "es": "Líbano",
        "en": "Lebanon",
        "pt_BR": "Líbano",
        "sr-Cyrl": "Либан",
        "sr-Latn": "Liban",
        "zh_TW": "黎巴嫩",
        "tr": "Lübnan",
        "ro": "Liban",
        "ar": "لبنان",
        "fa": "لبنان",
        "yue": "黎巴嫩"
      }
    },
    {
      "num_code": "438",
      "alpha_2_code": "LI",
      "alpha_3_code": "LIE",
      "en_short_name": "Liechtenstein",
      "nationality": "Liechtenstein",
      "dial_code": "+423",
      "nameTranslations": {
        "sk": "Lichtenštajnsko",
        "se": "Liechtenstein",
        "pl": "Liechtenstein",
        "no": "Liechtenstein",
        "ja": "リヒテンシュタイン",
        "it": "Liechtenstein",
        "zh": "列支敦士登",
        "nl": "Liechtenstein",
        "de": "Liechtenstein",
        "fr": "Liechtenstein",
        "es": "Liechtenstein",
        "en": "Liechtenstein",
        "pt_BR": "Liechtenstein",
        "sr-Cyrl": "Лихтенштајн",
        "sr-Latn": "Lihtenštajn",
        "zh_TW": "列支敦斯登",
        "tr": "Lihtenştayn",
        "ro": "Liechtenstein",
        "ar": "ليختنشتاين",
        "fa": "لیختن‌اشتاین",
        "yue": "列支敦士登"
      }
    },
    {
      "num_code": "440",
      "alpha_2_code": "LT",
      "alpha_3_code": "LTU",
      "en_short_name": "Lithuania",
      "nationality": "Lithuanian",
      "dial_code": "+370",
      "nameTranslations": {
        "sk": "Litva",
        "se": "Lietuva",
        "pl": "Litwa",
        "no": "Litauen",
        "ja": "リトアニア",
        "it": "Lituania",
        "zh": "立陶宛",
        "nl": "Litouwen",
        "de": "Litauen",
        "fr": "Lituanie",
        "es": "Lituania",
        "en": "Lithuania",
        "pt_BR": "Lituânia",
        "sr-Cyrl": "Литванија",
        "sr-Latn": "Litvanija",
        "zh_TW": "立陶宛",
        "tr": "Litvanya",
        "ro": "Lituania",
        "ar": "ليتوانيا",
        "fa": "لیتوانی",
        "yue": "立陶宛"
      }
    },
    {
      "num_code": "442",
      "alpha_2_code": "LU",
      "alpha_3_code": "LUX",
      "en_short_name": "Luxembourg",
      "nationality": "Luxembourg, Luxembourgish",
      "dial_code": "+352",
      "nameTranslations": {
        "sk": "Luxembursko",
        "se": "Luxembourg",
        "pl": "Luksemburg",
        "no": "Luxemburg",
        "ja": "ルクセンブルク",
        "it": "Lussemburgo",
        "zh": "卢森堡",
        "nl": "Luxemburg",
        "de": "Luxemburg",
        "fr": "Luxembourg",
        "es": "Luxemburgo",
        "en": "Luxembourg",
        "pt_BR": "Luxemburgo",
        "sr-Cyrl": "Луксенбург",
        "sr-Latn": "Luksenburg",
        "zh_TW": "盧森堡",
        "tr": "Lüksemburg",
        "ro": "Luxemburg",
        "ar": "لوكسمبورغ",
        "fa": "لوکزامبورگ",
        "yue": "盧森堡"
      }
    },
    {
      "num_code": "470",
      "alpha_2_code": "MT",
      "alpha_3_code": "MLT",
      "en_short_name": "Malta",
      "nationality": "Maltese",
      "dial_code": "+356",
      "nameTranslations": {
        "sk": "Malta",
        "se": "Málta",
        "pl": "Malta",
        "no": "Malta",
        "ja": "マルタ",
        "it": "Malta",
        "zh": "马耳他",
        "nl": "Malta",
        "de": "Malta",
        "fr": "Malte",
        "es": "Malta",
        "en": "Malta",
        "pt_BR": "Malta",
        "sr-Cyrl": "Малта",
        "sr-Latn": "Malta",
        "zh_TW": "馬爾他",
        "tr": "Malta",
        "ro": "Malta",
        "ar": "مالطا",
        "fa": "مالت",
        "yue": "馬耳他"
      }
    },
    {
      "num_code": "498",
      "alpha_2_code": "MD",
      "alpha_3_code": "MDA",
      "en_short_name": "Moldova (Republic of)",
      "nationality": "Moldovan",
      "dial_code": "+373",
      "nameTranslations": {
        "sk": "Moldavsko",
        "se": "Moldávia",
        "pl": "Mołdawia",
        "no": "Moldova",
        "ja": "モルドバ",
        "it": "Moldavia",
        "zh": "摩尔多瓦",
        "nl": "Moldavië",
        "de": "Republik Moldau",
        "fr": "Moldavie",
        "es": "Moldavia",
        "en": "Moldova",
        "pt_BR": "Moldova",
        "sr-Cyrl": "Молдавија",
        "sr-Latn": "Moldavija",
        "zh_TW": "摩爾多瓦",
        "tr": "Moldova",
        "ro": "Moldova",
        "ar": "مولدوفا",
        "fa": "مولداوی",
        "yue": "摩爾多瓦（共和國）"
      }
    },
    {
      "num_code": "492",
      "alpha_2_code": "MC",
      "alpha_3_code": "MCO",
      "en_short_name": "Monaco",
      "nationality": "Monégasque, Monacan",
      "dial_code": "+377",
      "nameTranslations": {
        "sk": "Monako",
        "se": "Monaco",
        "pl": "Monako",
        "no": "Monaco",
        "ja": "モナコ",
        "it": "Monaco",
        "zh": "摩纳哥",
        "nl": "Monaco",
        "de": "Monaco",
        "fr": "Monaco",
        "es": "Mónaco",
        "en": "Monaco",
        "pt_BR": "Mônaco",
        "sr-Cyrl": "Монако",
        "sr-Latn": "Monako",
        "zh_TW": "摩納哥",
        "tr": "Monako",
        "ro": "Monaco",
        "ar": "موناكو",
        "fa": "موناكو",
        "yue": "摩納哥"
      }
    },
    {
      "num_code": "496",
      "alpha_2_code": "MN",
      "alpha_3_code": "MNG",
      "en_short_name": "Mongolia",
      "nationality": "Mongolian",
      "dial_code": "+976",
      "nameTranslations": {
        "sk": "Mongolsko",
        "se": "Mongolia",
        "pl": "Mongolia",
        "no": "Mongolia",
        "ja": "モンゴル",
        "it": "Mongolia",
        "zh": "蒙古",
        "nl": "Mongolië",
        "de": "Mongolei",
        "fr": "Mongolie",
        "es": "Mongolia",
        "en": "Mongolia",
        "pt_BR": "Mongólia",
        "sr-Cyrl": "Монголија",
        "sr-Latn": "Mongolija",
        "zh_TW": "蒙古",
        "tr": "Moğolistan",
        "ro": "Mongolia",
        "ar": "منغوليا",
        "fa": "مغولستان",
        "yue": "蒙古"
      }
    },
    {
      "num_code": "499",
      "alpha_2_code": "ME",
      "alpha_3_code": "MNE",
      "en_short_name": "Montenegro",
      "nationality": "Montenegrin",
      "dial_code": "+382",
      "nameTranslations": {
        "sk": "Čierna Hora",
        "se": "Montenegro",
        "pl": "Czarnogóra",
        "no": "Montenegro",
        "ja": "モンテネグロ",
        "it": "Montenegro",
        "zh": "黑山",
        "nl": "Montenegro",
        "de": "Montenegro",
        "fr": "Monténégro",
        "es": "Montenegro",
        "en": "Montenegro",
        "pt_BR": "Montenegro",
        "sr-Cyrl": "Црна Гора",
        "sr-Latn": "Crna Gora",
        "zh_TW": "蒙特內哥羅",
        "tr": "Karadağ",
        "ro": "Muntenegru",
        "ar": "الجبل الأسود",
        "fa": "مونته‌نگرو",
        "yue": "黑山"
      }
    },
    {
      "num_code": "528",
      "alpha_2_code": "NL",
      "alpha_3_code": "NLD",
      "en_short_name": "Netherlands",
      "nationality": "Dutch, Netherlandic",
      "dial_code": "+31",
      "nameTranslations": {
        "sk": "Holandsko",
        "se": "Vuolleeatnamat",
        "pl": "Holandia",
        "no": "Nederland",
        "ja": "オランダ",
        "it": "Paesi Bassi",
        "zh": "荷兰",
        "nl": "Nederland",
        "de": "Niederlande",
        "fr": "Pays-Bas",
        "es": "Países Bajos",
        "en": "Netherlands",
        "pt_BR": "Países Baixos",
        "sr-Cyrl": "Холандија",
        "sr-Latn": "Holandija",
        "zh_TW": "荷蘭",
        "tr": "Hollanda",
        "ro": "Olanda",
        "ar": "هولندا",
        "fa": "هلند",
        "yue": "荷蘭"
      }
    },
    {
      "num_code": "578",
      "alpha_2_code": "NO",
      "alpha_3_code": "NOR",
      "en_short_name": "Norway",
      "nationality": "Norwegian",
      "dial_code": "+47",
      "nameTranslations": {
        "sk": "Nórsko",
        "se": "Norga",
        "pl": "Norwegia",
        "no": "Norge",
        "ja": "ノルウェー",
        "it": "Norvegia",
        "zh": "挪威",
        "nl": "Noorwegen",
        "de": "Norwegen",
        "fr": "Norvège",
        "es": "Noruega",
        "en": "Norway",
        "pt_BR": "Noruega",
        "sr-Cyrl": "Норвешка",
        "sr-Latn": "Norveška",
        "zh_TW": "挪威",
        "tr": "Norveç",
        "ro": "Norvegia",
        "ar": "النرويج",
        "fa": "نروژ",
        "yue": "挪威"
      }
    },
    {
      "num_code": "620",
      "alpha_2_code": "PT",
      "alpha_3_code": "PRT",
      "en_short_name": "Portugal",
      "nationality": "Portuguese",
      "dial_code": "+351",
      "nameTranslations": {
        "sk": "Portugalsko",
        "se": "Portugála",
        "pl": "Portugalia",
        "no": "Portugal",
        "ja": "ポルトガル",
        "it": "Portogallo",
        "zh": "葡萄牙",
        "nl": "Portugal",
        "de": "Portugal",
        "fr": "Portugal",
        "es": "Portugal",
        "en": "Portugal",
        "pt_BR": "Portugal",
        "sr-Cyrl": "Португалија",
        "sr-Latn": "Portugalija",
        "zh_TW": "葡萄牙",
        "tr": "Portekiz",
        "ro": "Portugalia",
        "ar": "البرتغال",
        "fa": "پرتغال",
        "yue": "葡萄牙"
      }
    },
    {
      "num_code": "642",
      "alpha_2_code": "RO",
      "alpha_3_code": "ROU",
      "en_short_name": "Romania",
      "nationality": "Romanian",
      "dial_code": "+40",
      "nameTranslations": {
        "sk": "Rumunsko",
        "se": "Románia",
        "pl": "Rumunia",
        "no": "Romania",
        "ja": "ルーマニア",
        "it": "Romania",
        "zh": "罗马尼亚",
        "nl": "Roemenië",
        "de": "Rumänien",
        "fr": "Roumanie",
        "es": "Rumanía",
        "en": "Romania",
        "pt_BR": "Romênia",
        "sr-Cyrl": "Румунија",
        "sr-Latn": "Rumunija",
        "zh_TW": "羅馬尼亞",
        "tr": "Romanya",
        "ro": "România",
        "ar": "رومانيا",
        "fa": "رومانی",
        "yue": "羅馬尼亞"
      }
    },
    {
      "num_code": "643",
      "alpha_2_code": "RU",
      "alpha_3_code": "RUS",
      "en_short_name": "Russian Federation",
      "nationality": "Russian",
      "dial_code": "+7",
      "nameTranslations": {
        "sk": "Rusko",
        "se": "Ruošša",
        "pl": "Rosja",
        "no": "Russland",
        "ja": "ロシア",
        "it": "Russia",
        "zh": "俄罗斯",
        "nl": "Rusland",
        "de": "Russland",
        "fr": "Russie",
        "es": "Rusia",
        "en": "Russia",
        "pt_BR": "Rússia",
        "sr-Cyrl": "Русија",
        "sr-Latn": "Rusija",
        "zh_TW": "俄羅斯",
        "tr": "Rusya",
        "ro": "Rusia",
        "ar": "روسيا",
        "fa": "روسیه",
        "yue": "俄儸斯聯邦"
      }
    },
    {
      "num_code": "688",
      "alpha_2_code": "RS",
      "alpha_3_code": "SRB",
      "en_short_name": "Serbia",
      "nationality": "Serbian",
      "dial_code": "+381",
      "nameTranslations": {
        "sk": "Srbsko",
        "se": "Serbia",
        "pl": "Serbia",
        "no": "Serbia",
        "ja": "セルビア",
        "it": "Serbia",
        "zh": "塞尔维亚",
        "nl": "Servië",
        "de": "Serbien",
        "fr": "Serbie",
        "es": "Serbia",
        "en": "Serbia",
        "pt_BR": "Sérvia",
        "sr-Cyrl": "Србија",
        "sr-Latn": "Srbija",
        "zh_TW": "塞爾維亞",
        "tr": "Sırbistan",
        "ro": "Serbia",
        "ar": "صربيا",
        "fa": "صربستان",
        "yue": "塞爾維亞"
      }
    },
    {
      "num_code": "705",
      "alpha_2_code": "SI",
      "alpha_3_code": "SVN",
      "en_short_name": "Slovenia",
      "nationality": "Slovenian, Slovene",
      "dial_code": "+386",
      "nameTranslations": {
        "sk": "Slovinsko",
        "se": "Slovenia",
        "pl": "Słowenia",
        "no": "Slovenia",
        "ja": "スロベニア",
        "it": "Slovenia",
        "zh": "斯洛文尼亚",
        "nl": "Slovenië",
        "de": "Slowenien",
        "fr": "Slovénie",
        "es": "Eslovenia",
        "en": "Slovenia",
        "pt_BR": "Eslovênia",
        "sr-Cyrl": "Словеније",
        "sr-Latn": "Slovenija",
        "zh_TW": "斯洛維尼亞",
        "tr": "Slovenya",
        "ro": "Slovenia",
        "ar": "سلوفينيا",
        "fa": "اسلوونی",
        "yue": "斯洛文尼亞"
      }
    },
    {
      "num_code": "724",
      "alpha_2_code": "ES",
      "alpha_3_code": "ESP",
      "en_short_name": "Spain",
      "nationality": "Spanish",
      "dial_code": "+34",
      "nameTranslations": {
        "sk": "Španielsko",
        "se": "Spánia",
        "pl": "Hiszpania",
        "no": "Spania",
        "ja": "スペイン",
        "it": "Spagna",
        "zh": "西班牙",
        "nl": "Spanje",
        "de": "Spanien",
        "fr": "Espagne",
        "es": "España",
        "en": "Spain",
        "pt_BR": "Espanha",
        "sr-Cyrl": "Шпанија",
        "sr-Latn": "Španija",
        "zh_TW": "西班牙",
        "tr": "İspanya",
        "ro": "Spania",
        "ar": "إسبانيا",
        "fa": "اسپانیا",
        "yue": "西班牙"
      }
    },
    {
      "num_code": "752",
      "alpha_2_code": "SE",
      "alpha_3_code": "SWE",
      "en_short_name": "Sweden",
      "nationality": "Swedish",
      "dial_code": "+46",
      "nameTranslations": {
        "sk": "Švédsko",
        "se": "Ruoŧŧa",
        "pl": "Szwecja",
        "no": "Sverige",
        "ja": "スウェーデン",
        "it": "Svezia",
        "zh": "瑞典",
        "nl": "Zweden",
        "de": "Schweden",
        "fr": "Suède",
        "es": "Suecia",
        "en": "Sweden",
        "pt_BR": "Suécia",
        "sr-Cyrl": "Шведска",
        "sr-Latn": "Švedska",
        "zh_TW": "瑞典",
        "tr": "İsveç",
        "ro": "Suedia",
        "ar": "السويد",
        "fa": "سوئد",
        "yue": "瑞典"
      }
    },
    {
      "num_code": "756",
      "alpha_2_code": "CH",
      "alpha_3_code": "CHE",
      "en_short_name": "Switzerland",
      "nationality": "Swiss",
      "dial_code": "+41",
      "nameTranslations": {
        "sk": "Švajčiarsko",
        "se": "Šveica",
        "pl": "Szwajcaria",
        "no": "Sveits",
        "ja": "スイス",
        "it": "Svizzera",
        "zh": "瑞士",
        "nl": "Zwitserland",
        "de": "Schweiz",
        "fr": "Suisse",
        "es": "Suiza",
        "en": "Switzerland",
        "pt_BR": "Suíça",
        "sr-Cyrl": "Швајцарска",
        "sr-Latn": "Švajcarska",
        "zh_TW": "瑞士",
        "tr": "İsviçre",
        "ro": "Elveţia",
        "ar": "سويسرا",
        "fa": "سوئیس",
        "yue": "瑞士"
      }
    },
    {
      "num_code": "792",
      "alpha_2_code": "TR",
      "alpha_3_code": "TUR",
      "en_short_name": "Turkey",
      "nationality": "Turkish",
      "dial_code": "+90",
      "nameTranslations": {
        "sk": "Turecko",
        "se": "Durka",
        "pl": "Turcja",
        "no": "Tyrkia",
        "ja": "トルコ",
        "it": "Turchia",
        "zh": "土耳其",
        "nl": "Turkije",
        "de": "Türkei",
        "fr": "Turquie",
        "es": "Turquía",
        "en": "Turkey",
        "pt_BR": "Peru",
        "sr-Cyrl": "Турска",
        "sr-Latn": "Turska",
        "zh_TW": "土耳其",
        "tr": "Türkiye",
        "ro": "Turcia",
        "ar": "تركيا",
        "fa": "ترکیه",
        "yue": "土耳其"
      }
    },
    {
      "num_code": "804",
      "alpha_2_code": "UA",
      "alpha_3_code": "UKR",
      "en_short_name": "Ukraine",
      "nationality": "Ukrainian",
      "dial_code": "+380",
      "nameTranslations": {
        "sk": "Ukrajina",
        "se": "Ukraina",
        "pl": "Ukraina",
        "no": "Ukraina",
        "ja": "ウクライナ",
        "it": "Ucraina",
        "zh": "乌克兰",
        "nl": "Oekraïne",
        "de": "Ukraine",
        "fr": "Ukraine",
        "es": "Ucrania",
        "en": "Ukraine",
        "pt_BR": "Ucrânia",
        "sr-Cyrl": "Украјина",
        "sr-Latn": "Ukrajina",
        "zh_TW": "烏克蘭",
        "tr": "Ukrayna",
        "ro": "Ucraína",
        "ar": "أوكرانيا",
        "fa": "اوکراین",
        "yue": "烏克蘭"
      }
    },
    {
      "num_code": "826",
      "alpha_2_code": "GB",
      "alpha_3_code": "GBR",
      "en_short_name": "United Kingdom of Great Britain and Northern Ireland",
      "nationality": "British, UK",
      "dial_code": "+44",
      "nameTranslations": {
        "sk": "Spojené kráľovstvo",
        "se": "Stuorra-Británnia",
        "pl": "Wielka Brytania",
        "no": "Storbritannia",
        "ja": "イギリス",
        "it": "Regno Unito",
        "zh": "英国",
        "nl": "Verenigd Koninkrijk",
        "de": "Vereinigtes Königreich",
        "fr": "Royaume-Uni",
        "es": "Reino Unido",
        "en": "United Kingdom",
        "pt_BR": "Reino Unido",
        "sr-Cyrl": "Уједињено Краљевство",
        "sr-Latn": "Ujedinjeno Kraljevstvo",
        "zh_TW": "英國",
        "tr": "Büyük Britanya ve Kuzey İrlanda Birleşik Krallığ",
        "ro": "Regatul Unit al Marii Britanii și Irlandei de Nord",
        "ar": "المملكة المتحدة",
        "fa": "بریتانیا",
        "yue": "大不列顛及北愛爾蘭聯合王國"
      }
    },
  ];
}
